const PROJECTS = {
  hejdoktor: {
    name: 'HejDoktor<em>.dk</em>',
    year: '2024',
    tags: [{ label: 'Web Design', accent: true }, { label: 'UI/UX' }],
    tech: ['Figma', 'UX Research', 'Prototyping'],
    img: 'https://pub-752aa4b9003c4c9782da7672bd7acb76.r2.dev/Hej%20Doktor.png',
    accent: '#7c5cbf',
    heroBg: '#1a1040',
    tagline: 'Redesign af Danmarks førende online lægeplatform.',
    brief: 'HejDoktor.dk kontaktede os med et klart mål: modernisere en forældet platform og øge konverteringsraten markant. Platformen betjener over 2 millioner danskere månedligt.',
    challenge: 'Den eksisterende platform var bygget i 2017 og led under forvirrende brugerflow, lav mobiloptimering og høj afvisningsprocent. Brugerne opgav processen halvvejs.',
    solution: 'Vi redesignede hele UX-flowet fra bunden — forenklede onboarding til 3 trin, optimerede til mobile-first og indførte et nyt designsystem baseret på klarhed og tillid.',
    outcome: 'Konverteringsraten steg med 65% inden for de første 8 uger. Afvisningsprocenten faldt med 38%, og brugertilfredsscoren steg til 4.7/5.',
    stats: [
      { val: 65,  unit: '%',     label: 'Stigning i konvertering' },
      { val: 38,  unit: '%',     label: 'Fald i afvisningsrate' },
      { val: 3,   unit: ' uger', label: 'Fra brief til levering' },
      { val: 47,  unit: 'k',     label: 'Månedlige aktive brugere' },
    ],
    results: [
      'Forvirrende booking-flow reduceret fra 9 trin til 3 — uden at miste information.',
      'Ny komponentbibliotek i Figma adopted af hele produktteamet som standard.',
      'Mobilkonvertering steg med 72% alene på baggrund af UX-optimeringer.',
    ],
    next: 'jobnet',
  },

  jobnet: {
    name: 'Jobnet',
    year: '2023',
    tags: [{ label: 'UI/UX', accent: true }, { label: 'Gov. Platform' }],
    tech: ['UX Research', 'Figma', 'Accessibility'],
    img: 'https://pub-752aa4b9003c4c9782da7672bd7acb76.r2.dev/Jobnet.png',
    accent: '#1e7abf',
    heroBg: '#0d2137',
    tagline: 'UX-strategi og redesign af Danmarks nationale jobportal.',
    brief: 'Styrelsen for Arbejdsmarked og Rekruttering engagerede Remently til at gennemgå og redesigne Jobnet — platformen der bruges af 1,8 millioner danskere til jobsøgning hvert år.',
    challenge: 'Jobnet var præget af forældet informationsarkitektur, lav tilgængelighed og en fragmenteret mobiloplevelse. Borgere med lavere digital kompetence opgav platformen.',
    solution: 'Vi kortlagde 47 unikke brugerrejser, redesignede informationsarkitekturen og skabte et tilgængeligt UI-komponentbibliotek der møder WCAG 2.1 AA-standarden.',
    outcome: 'Drop-off raten faldt med 30%. Brugertilfredsscoren steg fra 2.9 til 4.2/5. Designsystemet er adopteret som standard på tværs af ministeriet.',
    stats: [
      { val: 30, unit: '%',     label: 'Fald i drop-off rate' },
      { val: 47, unit: '',      label: 'Kortlagte brugerrejser' },
      { val: 6,  unit: ' uger', label: 'Projektlængde' },
      { val: 18, unit: 'M',     label: 'Årlige besøg' },
    ],
    results: [
      'Informationsarkitekturen reduceret fra 7 niveauer til 3 — uden at miste indhold.',
      'Alle kritiske flows godkendt som WCAG 2.1 AA-kompatible efter redesign.',
      'Designsystemet adopteret som officiel standard på tværs af 4 ministerier.',
    ],
    next: 'dentaaid',
  },

  dentaaid: {
    name: 'DentaAid',
    year: '2024',
    tags: [{ label: 'Web Design', accent: true }, { label: 'Branding' }],
    tech: ['Shopify', 'Branding', 'Motion Design'],
    img: 'https://pub-752aa4b9003c4c9782da7672bd7acb76.r2.dev/Dentaaid.png',
    accent: '#0d9488',
    heroBg: '#0a1a1a',
    tagline: 'Brand-identitet og landingsside for en moderne dental telehealth service.',
    brief: 'DentaAid kom til os som en idé på en serviet. Vi byggede alt fra nul: navn, logo, farvepalette, tone of voice og en konverteringsoptimeret Shopify-landingsside.',
    challenge: 'Telehealth-markedet er overbefolket med generiske brands. DentaAid skulle skille sig ud med professionalisme og varme — og konvertere i en kategori med høj skepsis.',
    solution: 'Vi udviklede en teal-baseret brandidentitet med rene linjer og menneskelige billeder. Landingssiden er bygget med et klinisk men tilgængeligt udtryk med stærke sociale beviser.',
    outcome: 'DentaAid solgte ud af pilotprogrammet inden for 72 timer efter lancering. Landingssiden konverterer 8.4% fra organisk trafik mod branchesnittet på 2–3%.',
    stats: [
      { val: 8,  unit: '.4%',   label: 'Konverteringsrate' },
      { val: 72, unit: 't',     label: 'Til udsolgt pilot' },
      { val: 4,  unit: ' uger', label: 'Fra brief til live' },
      { val: 3,  unit: 'x',     label: 'ROI inden for 3 mdr.' },
    ],
    results: [
      'Komplet brand-identitet skabt fra nul — logo, farver, typografi og tone of voice.',
      'Landingssiden konverterer 8.4% fra kold organisk trafik — 3x branchesnittet.',
      'Pilotprogram udsolgt 72 timer efter lancering udelukkende via landingssiden.',
    ],
    next: 'brotego',
  },

  brotego: {
    name: 'Brotego',
    year: '2024',
    tags: [{ label: 'E-commerce', accent: true }, { label: 'Mobile Design' }],
    tech: ['Shopify', 'CRO', 'Mobile First'],
    img: 'https://pub-752aa4b9003c4c9782da7672bd7acb76.r2.dev/Brotego.png',
    accent: '#c9a84c',
    heroBg: '#111111',
    tagline: 'Fuldt Shopify-build for et premium mandepleje-brand.',
    brief: 'Brotego ville ind på et af de hurtigst voksende segmenter i skandinavisk e-commerce: premium grooming til mænd. De havde produktet — vi byggede oplevelsen.',
    challenge: 'Den eksisterende løsning var et standard Shopify-tema der ikke afspejlede brandets premium-positionering. Konverteringsraten lå på 1.2% og mobiloplevelsen var dårlig.',
    solution: 'Vi byggede et custom Shopify-theme fra bunden: bold typografi, cinema-inspireret æstetik, lynhurtige produktsider og et mobile-first checkout-flow optimeret til impulskøb.',
    outcome: 'Konverteringsraten steg fra 1.2% til 3.8% — over 200% stigning. Mobilsalget voksede til 78% af al omsætning. AOV steg med 34% efter implementering af bundle-logik.',
    stats: [
      { val: 216, unit: '%',     label: 'Stigning i konvertering' },
      { val: 78,  unit: '%',     label: 'Af salg via mobil' },
      { val: 34,  unit: '%',     label: 'Stigning i AOV' },
      { val: 3,   unit: ' uger', label: 'Fra brief til lancering' },
    ],
    results: [
      'Custom Shopify-theme bygget fra bunden — ingen generiske templates.',
      'Mobilkonvertering tredoblet med mobile-first checkout og sticky add-to-cart.',
      'Bundle-upsell logik øgede gennemsnitlig ordreværdi med 34% allerede i uge 1.',
    ],
    next: 'hejdoktor',
  },
};

const NEXT_NAMES = {
  hejdoktor: 'Hejdoktor.dk',
  jobnet: 'Jobnet',
  dentaaid: 'DentaAid',
  brotego: 'Brotego',
};
